<?php
namespace notifyy;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-10 at 12:54:30.
 */
class BuilderTest extends \PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * Test building the adapter
     *
     * @dataProvider buildProvider
     */
    public function testBuild($mAdapter, $mConfig = null) {
        $oNotifier = Builder::build($mAdapter, $mConfig);
        $this->assertInstanceOf('\notifyy\Notifyable', $oNotifier);
    }

    /**
     * Return some working arguments
     *
     * @return array
     */
    public function buildProvider() {
        return array(
            array(
                'stdout',
                null
            ),
            array(
                'GroWl'
            ),
            array(
                'LIBNOTIFY',
                new \stdClass()
            ),
            array(
                'File',
                array(
                    'path' => '/tmp'
                )
            ),
            array(
                'File',
                array(
                )
            ),
            array(
                '\\notifyy\\Adapter\\libnotify'
            ),
            array(
                new \notifyy\Adapter\Growl()
            )
        );
    }

    /**
     * Test a failing build
     */
    public function testFailingBuild() {
        $this->setExpectedException('\notifyy\Exception', \notifyy\Exception::UNKNOWN_ADAPTER);
        Builder::build('test');
    }
}
