<?php
/**
 * Test class for Dbus.
 * Generated by PHPUnit on 2011-10-22 at 23:00:50.
 */
namespace notifyy\Adapter;

class DbusTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Dbus
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->_object = new Dbus();
    }

    /**
     * Test simple notify call
     */
    public function testNotify() {
        $sText = md5(time());
        $this->assertInstanceOf('\notifyy\AbstractAdapter', $this->_object->notify(
            \notifyy\AbstractAdapter::SUCCESS,
            $sText
        ));
    }
}
