<?php
/**
 * Test class for Libnotify.
 * Generated by PHPUnit on 2011-10-22 at 23:00:50.
 */
namespace notifyy\Adapter;

class LibnotifyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Libnotify
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->_object = new Libnotify();
    }

    /**
     * Test simple notify call
     */
    public function testNotify() {
        $sText = sprintf('%s: %s', 'libnotify', md5(time()));
        $this->assertInstanceOf('\notifyy\AbstractAdapter', $this->_object->notify(
            \notifyy\Notifyable::SUCCESS,
            $sText
        ));
    }
}
