<?php
/**
 * Test class for Stdout.
 * Generated by PHPUnit on 2011-10-22 at 23:00:50.
 */
namespace notifyy\Adapter;

class StdoutTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Stdout
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->_object = new Stdout();
        $this->_object->setConfig();
    }

    /**
     * Test simple add call
     */
    public function testNotify() {
        $sText = md5(time());
        $this->assertInstanceOf('\notifyy\AbstractAdapter', $this->_object->notify(
            \notifyy\Notifyable::SUCCESS,
            $sText
        ));

        $this->expectOutputRegex(sprintf('/%s/', $sText));
    }
}
